;;; directories.el --- Configurations for org-mode
;;;
;;; Commentary:
;;;
;;; Configurations here apply to org files.
;;;
;;; Code:

;; Set up org-mode
(use-package org
  :demand
  :init (setq org-tags-column 0
              org-log-done 'time
              org-log-repeat nil
              org-agenda-files (list "~/Notes/Personal.org")
              org-agenda-window-setup 'only-window
              org-agenda-custom-commands '(("p" . "Personal searches")
                                           ("pc" tags-todo "+2019_Subaru_Ascent")
                                           ("ph" tags-todo "+720_Natoma_Drive")
                                           ("ps" tags-todo "+shakti")
                                           ("pp" tags-todo "-shakti-720_Natoma_Drive-2019_Subaru_Ascent")))
  :general
  ('(normal motion emacs)
   "SPC aa" '(org-agenda :which-key "Agenda"))
  ('(normal motion emacs)
   :prefix "SPC eo"
   "" '(:ignore t :which-key "Org links")
   "y" '(org-store-link :which-key "yank")
   "p" '(org-insert-link :which-key "insert")))
(use-package evil-org
  :delight
  :after org
  :functions evil-org-agenda-set-keys
  :hook ((org-mode . evil-org-mode)
         (evil-org-mode . evil-org-set-key-theme))
  :config
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))

;; Use pretty bullets in org-mode
(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode))

;; TODO https://github.com/IvanMalison/org-projectile
;; TODO https://github.com/ahungry/org-jira
;; TODO https://code.orgmode.org/bzg/org-mode/raw/master/contrib/lisp/org-contacts.el
;; TODO org-mu4e



;; (25 . org-yank)
;; (11 . org-kill-line)
;; (5 . org-end-of-line)
;; (1 . org-beginning-of-line)
;; (67108899 . org-table-rotate-recalc-marks)
;; (10 . org-return-indent)
;; (13 . org-return)
;; (67108903 . org-cycle-agenda-files)
;; (67108908 . org-cycle-agenda-files)
;; (C-S-return . org-insert-todo-heading-respect-content)
;; (C-return . org-insert-heading-respect-content)
;; (124 . org-force-self-insert)
;; (C-S-down . org-shiftcontroldown)
;; (C-S-up . org-shiftcontrolup)
;; (C-S-left . org-shiftcontrolleft)
;; (C-S-right . org-shiftcontrolright)
;; (S-right . org-shiftright)
;; (S-left . org-shiftleft)
;; (S-down . org-shiftdown)
;; (S-up . org-shiftup)
;; (M-S-down . org-shiftmetadown)
;; (M-S-up . org-shiftmetaup)
;; (M-S-right . org-shiftmetaright)
;; (M-S-left . org-shiftmetaleft)
;; (C-M-S-left . org-decrease-number-at-point)
;; (C-M-S-right . org-increase-number-at-point)
;; (M-down . org-metadown)
;; (M-up . org-metaup)
;; (M-right . org-metaright)
;; (M-left . org-metaleft)
;; (M-S-return . org-insert-todo-heading)
;; (S-return . org-table-copy-down)
;; (backtab . org-shifttab)
;; (S-tab . org-shifttab)
;; (S-iso-lefttab . org-shifttab)
;; (27 keymap
;;     (101 . org-forward-sentence)
;;     (97 . org-backward-sentence)
;;     (104 . org-mark-element)
;;     (94 . org-delete-indentation)
;;     (123 . org-backward-element)
;;     (125 . org-forward-element)
;;     (20 . org-transpose-element)
;;     (S-down . org-shiftmetadown)
;;     (S-up . org-shiftmetaup)
;;     (S-right . org-shiftmetaright)
;;     (S-left . org-shiftmetaleft)
;;     (S-return . org-insert-todo-heading)
;;     (tab . pcomplete)
;;     (down . org-metadown)
;;     (up . org-metaup)
;;     (right . org-metaright)
;;     (left . org-metaleft)
;;     (return . org-meta-return)
;;     (13 . org-meta-return)
;;     (9 . pcomplete))
;; (C-tab . org-force-cycle-archived)
;; (tab . org-cycle)
;; (9 . org-cycle)
;; (3 keymap
;;    (67108906 . org-list-make-subtree)
;;    (64 . org-mark-subtree)
;;    (58 . org-toggle-fixed-width)
;;    (5 . org-export-dispatch)
;;    (123 . org-table-toggle-formula-debugger)
;;    (125 . org-table-toggle-coordinate-overlays)
;;    (126 . org-table-create-with-table\.el)
;;    (124 . org-table-create-or-convert-from-region)
;;    (34 keymap
;;        (103 . org-plot/gnuplot)
;;        (97 . orgtbl-ascii-plot))
;;    (96 . org-table-edit-field)
;;    (39 . org-edit-special)
;;    (61 . org-table-eval-formula)
;;    (43 . org-table-sum)
;;    (32 . org-table-blank-field)
;;    (63 . org-table-field-info)
;;    (35 . org-update-statistics-cookies)
;;    (11 . org-kill-note-or-show-branches)
;;    (3 . org-ctrl-c-ctrl-c)
;;    (94 . org-sort)
;;    (42 . org-ctrl-c-star)
;;    (45 . org-ctrl-c-minus)
;;    (93 . org-remove-file)
;;    (91 . org-agenda-file-to-front)
;;    (60 . org-date-from-calendar)
;;    (62 . org-goto-calendar)
;;    (25 . org-evaluate-time-range)
;;    (44 . org-priority)
;;    (33 . org-time-stamp-inactive)
;;    (46 . org-time-stamp)
;;    (26 . org-add-note)
;;    (38 . org-mark-ring-goto)
;;    (37 . org-mark-ring-push)
;;    (15 . org-open-at-point)
;;    (12 . org-insert-link)
;;    (13 . org-ctrl-c-ret)
;;    (92 . org-match-sparse-tree)
;;    (47 . org-sparse-tree)
;;    (23 . org-refile)
;;    (59 . org-toggle-comment)
;;    (4 . org-deadline)
;;    (19 . org-schedule)
;;    (17 . org-set-tags-command)
;;    (20 . org-todo)
;;    (10 . org-goto)
;;    (36 . org-archive-subtree)
;;    (27 keymap
;;        (12 . org-insert-all-links)
;;        (108 . org-insert-last-stored-link)
;;        (119 . org-copy)
;;        (98 . org-previous-block)
;;        (102 . org-next-block))
;;    (2 . org-backward-heading-same-level)
;;    (6 . org-forward-heading-same-level)
;;    (31 . org-down-element)
;;    (30 . org-up-element)
;;    (18 . org-reveal)
;;    (1 . org-attach)
;;    (right . org-shiftright)
;;    (left . org-shiftleft)
;;    (down . org-shiftdown)
;;    (up . org-shiftup)
;;    (22 keymap
;;        (27 keymap
;;            (8 . org-babel-mark-block))
;;        (107 . org-babel-remove-result-one-or-many)
;;        (120 . org-babel-do-key-sequence-in-edit-buffer)
;;        (24 . org-babel-do-key-sequence-in-edit-buffer)
;;        (104 . org-babel-describe-bindings)
;;        (97 . org-babel-sha1-hash)
;;        (1 . org-babel-sha1-hash)
;;        (122 . org-babel-switch-to-session-with-code)
;;        (26 . org-babel-switch-to-session)
;;        (73 . org-babel-view-src-block-info)
;;        (105 . org-babel-lob-ingest)
;;        (9 . org-babel-view-src-block-info)
;;        (108 . org-babel-load-in-session)
;;        (12 . org-babel-load-in-session)
;;        (106 . org-babel-insert-header-arg)
;;        (10 . org-babel-insert-header-arg)
;;        (99 . org-babel-check-src-block)
;;        (3 . org-babel-check-src-block)
;;        (102 . org-babel-tangle-file)
;;        (6 . org-babel-tangle-file)
;;        (116 . org-babel-tangle)
;;        (20 . org-babel-tangle)
;;        (100 . org-babel-demarcate-block)
;;        (4 . org-babel-demarcate-block)
;;        (115 . org-babel-execute-subtree)
;;        (19 . org-babel-execute-subtree)
;;        (98 . org-babel-execute-buffer)
;;        (2 . org-babel-execute-buffer)
;;        (18 . org-babel-goto-named-result)
;;        (114 . org-babel-goto-named-result)
;;        (103 . org-babel-goto-named-src-block)
;;        (21 . org-babel-goto-src-block-head)
;;        (117 . org-babel-goto-src-block-head)
;;        (118 . org-babel-expand-src-block)
;;        (22 . org-babel-expand-src-block)
;;        (15 . org-babel-open-src-block-result)
;;        (111 . org-babel-open-src-block-result)
;;        (5 . org-babel-execute-maybe)
;;        (101 . org-babel-execute-maybe)
;;        (14 . org-babel-next-src-block)
;;        (110 . org-babel-next-src-block)
;;        (16 . org-babel-previous-src-block)
;;        (112 . org-babel-previous-src-block))
;;    (24 keymap
;;        (91 . org-reftex-citation)
;;        (71 . org-feed-goto-inbox)
;;        (103 . org-feed-update-all)
;;        (33 . org-reload)
;;        (3 . org-columns)
;;        (44 . org-timer-pause-or-continue)
;;        (95 . org-timer-stop)
;;        (48 . org-timer-start)
;;        (45 . org-timer-item)
;;        (46 . org-timer)
;;        (59 . org-timer-set-timer)
;;        (105 . org-columns-insert-dblock)
;;        (111 . org-toggle-ordered-property)
;;        (69 . org-inc-effort)
;;        (101 . org-set-effort)
;;        (80 . org-set-property-and-value)
;;        (112 . org-set-property)
;;        (2 . org-toggle-checkbox)
;;        (92 . org-toggle-pretty-entities)
;;        (22 . org-toggle-inline-images)
;;        (12 . org-toggle-latex-fragment)
;;        (21 . org-dblock-update)
;;        (18 . org-clock-report)
;;        (4 . org-clock-display)
;;        (17 . org-clock-cancel)
;;        (10 . org-clock-goto)
;;        (15 . org-clock-out)
;;        (26 . org-resolve-clocks)
;;        (24 . org-clock-in-last)
;;        (9 . org-clock-in)
;;        (20 . org-toggle-time-stamp-overlays)
;;        (25 . org-paste-special)
;;        (27 keymap
;;            (22 . org-redisplay-inline-images)
;;            (119 . org-copy-special))
;;        (23 . org-cut-special)
;;        (13 keymap
;;            (112 . org-mobile-push)
;;            (103 . org-mobile-pull))
;;        (102 . org-footnote-action)
;;        (6 . org-emphasize)
;;        (62 . org-agenda-remove-restriction-lock)
;;        (60 . org-agenda-set-restriction-lock)
;;        (16 . org-previous-link)
;;        (14 . org-next-link)
;;        (118 . org-copy-visible)
;;        (113 . org-toggle-tags-groups)
;;        (98 . org-tree-to-indirect-buffer)
;;        (65 . org-archive-to-archive-sibling)
;;        (97 . org-toggle-archive-tag)
;;        (1 . org-archive-subtree-default)
;;        (19 . org-archive-subtree)
;;        (left . org-shiftcontrolleft)
;;        (right . org-shiftcontrolright)
;;        (68 . org-shiftmetadown)
;;        (85 . org-shiftmetaup)
;;        (82 . org-shiftmetaright)
;;        (76 . org-shiftmetaleft)
;;        (100 . org-insert-drawer)
;;        (117 . org-metaup)
;;        (114 . org-metaright)
;;        (108 . org-metaleft)
;;        (109 . org-meta-return)
;;        (77 . org-insert-todo-heading)
;;        (99 . org-clone-subtree-with-time-shift)))
;; (remap keymap
;;        (fill-paragraph . org-fill-paragraph)
;;        (transpose-words . org-transpose-words)
;;        (backward-paragraph . org-backward-paragraph)
;;        (forward-paragraph . org-forward-paragraph)
;;        (comment-dwim . org-comment-dwim)
;;        (open-line . org-open-line)
;;        (delete-backward-char . org-delete-backward-char)
;;        (delete-char . org-delete-char)
;;        (self-insert-command . org-self-insert-command)
;;        (show-children . org-show-children)
;;        (outline-previous-visible-heading . org-previous-visible-heading)
;;        (outline-next-visible-heading . org-next-visible-heading)
;;        (outline-insert-heading . org-ctrl-c-ret)
;;        (outline-demote . org-demote-subtree)
;;        (outline-promote . org-promote-subtree)
;;        (outline-show-branches . org-kill-note-or-show-branches)
;;        (outline-backward-same-level . org-backward-heading-same-level)
;;        (outline-forward-same-level . org-forward-heading-same-level)
;;        (outline-show-subtree . org-show-subtree)
;;        (outline-mark-subtree . org-mark-subtree))
;; keymap
;; (normal-state keymap "Auxiliary keymap for Normal state"
;;               (M-return . outline-insert-heading)
;;               (27 keymap
;;                   (108 . outline-demote)
;;                   (107 . outline-move-subtree-up)
;;                   (106 . outline-move-subtree-down)
;;                   (104 . outline-promote))
;;               (94 . outline-up-heading)
;;               (103 keymap
;;                    (106 . outline-forward-same-level)
;;                    (107 . outline-backward-same-level))
;;               (10 . outline-forward-same-level)
;;               (11 . outline-backward-same-level)
;;               (93 . outline-next-visible-heading)
;;               (91 . outline-previous-visible-heading)
;;               (122 keymap
;;                    (112 . outline-hide-other)
;;                    (107 . outline-show-children)
;;                    (75 . outline-show-branches)
;;                    (108 . outline-hide-leaves)
;;                    (101 . outline-show-entry)
;;                    (98 . outline-hide-entry)
;;                    (66 . outline-hide-body))
;;               (tab . outline-toggle-children)
;;               (backtab . outline-show-all))
;; (3 keymap
;;    (13 . outline-insert-heading)
;;    (67108926 . outline-demote)
;;    (67108924 . outline-promote)
;;    (22 . outline-move-subtree-down)
;;    (30 . outline-move-subtree-up)
;;    (15 . outline-hide-other)
;;    (17 . outline-hide-sublevels)
;;    (11 . outline-show-branches)
;;    (12 . outline-hide-leaves)
;;    (5 . outline-show-entry)
;;    (3 . outline-hide-entry)
;;    (1 . outline-show-all)
;;    (20 . outline-hide-body)
;;    (2 . outline-backward-same-level)
;;    (6 . outline-forward-same-level)
;;    (21 . outline-up-heading)
;;    (4 . outline-hide-subtree)
;;    (19 . outline-show-subtree)
;;    (9 . outline-show-children)
;;    (16 . outline-previous-visible-heading)
;;    (14 . outline-next-visible-heading)
;;    (64 . outline-mark-subtree))
;; (27 keymap
;;     (9 . ispell-complete-word)))




















(provide 'org)
;;; org.el ends here
