#!/bin/sh

SHAKTI_SOURCE="/home/cprussin/Projects/shakti/Sources/shakti"

red="\033[1;31m"
white="\033[1;37m"
reset="\033[0m"

restart_nginx() {
    echo -e "${white}> Restarting nginx...$reset"
    sudo systemctl restart nginx
    echo -e "\n"
}

clear_cache() {
    echo -e "${white}> Removing node_modules and clearing cache...$reset"
    npx gulp clearCache
    rm -rf node_modules packages/*/node_modules
    echo -e "\n"
}

clear_generated() {
    echo -e "${white}> Removing tmp and generated...$reset"
    rm -rf tmp generated
    echo -e "\n"
}

meatronulate() {
    echo -e "${white}> metatron refresh...$reset"
    metatron refresh
    echo -e "\n"
}

install_yarn() {
    echo -e "${white}> yarn...$reset"
    yarn
    echo -e "\n"
}

build() {
    echo -e "${white}> gulp build...$reset"
    npx gulp build
    echo -e "\n"
}

start() {
    echo -e "${white}> gulp...$reset"
    npx gulp
    echo -e "\n"
}

pushd $SHAKTI_SOURCE >/dev/null

case "$1" in
    fast) ;;
    fastcodex)
        clear_cache
        build
        ;;
    fullbruno)
        clear_cache
        clear_generated
        meatronulate
        install_yarn
        build
        ;;
    *)
        meatronulate
        install_yarn
        build
        ;;
esac
restart_nginx
start
popd >/dev/null
