{epkgs}: [
  epkgs.aggressive-indent
  epkgs.all-the-icons
  epkgs.calfw
  epkgs.calfw-org
  epkgs.company
  epkgs.company-emoji
  epkgs.company-quickhelp
  epkgs.counsel
  epkgs.counsel-projectile
  epkgs.csv-mode
  epkgs.delight
  epkgs.dhall-mode
  epkgs.direnv
  epkgs.dockerfile-mode
  epkgs.editorconfig
  epkgs.emojify
  epkgs.evil
  epkgs.evil-collection
  epkgs.evil-goggles
  epkgs.evil-org
  epkgs.evil-smartparens
  epkgs.flycheck
  epkgs.flycheck-popup-tip
  epkgs.general
  epkgs.git-gutter
  epkgs.git-timemachine
  epkgs.go-mode
  epkgs.good-scroll
  epkgs.graphql-mode
  epkgs.groovy-mode
  epkgs.haskell-mode
  epkgs.hass
  epkgs.helpful
  epkgs.highlight-numbers
  epkgs.hl-todo
  epkgs.imenu-list
  epkgs.indent-guide
  epkgs.ivy
  epkgs.jest
  epkgs.json-mode
  epkgs.kotlin-mode
  epkgs.link-hint
  epkgs.magit
  epkgs.markdown-mode
  epkgs.mmm-mode
  epkgs.mode-icons
  epkgs.nix-mode
  epkgs.org
  epkgs.org-bullets
  epkgs.org-roam
  epkgs.pdf-tools
  epkgs.pkg-info
  epkgs.powerline
  epkgs.powerline-evil
  epkgs.projectile
  epkgs.psc-ide
  epkgs.purescript-mode
  epkgs.rainbow-delimiters
  epkgs.rainbow-mode
  epkgs.rust-mode
  epkgs.scad-mode
  epkgs.smartparens
  epkgs.solarized-theme
  epkgs.swiper
  epkgs.treesit-grammars.with-all-grammars
  epkgs.tide
  epkgs.undo-tree
  epkgs.unicode-fonts
  epkgs.use-package
  epkgs.websocket
  epkgs.which-key
  epkgs.ws-butler
  epkgs.yaml-mode
  epkgs.zoom-frm
]
