#!/bin/sh
# Override some libraries to avoid incompatibillity
export LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so'
exec $HOME/.steam/steam/steamapps/common/Factorio/bin/x64/factorio
