#!/bin/sh

exec qemu-system-x86_64 \
     -enable-kvm -machine type=pc,accel=kvm \
     -cpu host \
     -m 1G \
     -net nic \
     -net user,smb=$HOME/Software \
     -usb -device usb-tablet \
     $HOME/Software/Microsoft/Windows\ 7\ VM.iso
