{
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
      MIIDATCCAqegAwIBAgIBATAKBggqhkjOPQQDAjCBxDELMAkGA1UEBhMCVVMxEzAR
      BgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCUxvcyBHYXRvczEtMCsGA1UEAwwk
      TmV0ZmxpeCBJbnRlcm5hbCBTZXJ2aWNlcyBSb290IENBIFYxMRQwEgYDVQQKDAtO
      ZXRmbGl4IEluYzEaMBgGA1UECwwRUGxhdGZvcm0gU2VjdXJpdHkxKzApBgkqhkiG
      9w0BCQEWHHBsYXRmb3Jtc2VjdXJpdHlAbmV0ZmxpeC5jb20wHhcNMTgwNDIyMTYy
      NzM5WhcNNDgwNDIzMTYyNzM5WjCBxDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNh
      bGlmb3JuaWExEjAQBgNVBAcMCUxvcyBHYXRvczEtMCsGA1UEAwwkTmV0ZmxpeCBJ
      bnRlcm5hbCBTZXJ2aWNlcyBSb290IENBIFYxMRQwEgYDVQQKDAtOZXRmbGl4IElu
      YzEaMBgGA1UECwwRUGxhdGZvcm0gU2VjdXJpdHkxKzApBgkqhkiG9w0BCQEWHHBs
      YXRmb3Jtc2VjdXJpdHlAbmV0ZmxpeC5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMB
      BwNCAAQT2rnh3YNwWWZxUDOuPQS55uRcMc6RxNxf0K6mPmmRbRZv7Td08lEjVfm/
      hRTjRf7899NqTJB0w5FOxvkZR3uvo4GHMIGEMA4GA1UdDwEB/wQEAwIBhjAdBgNV
      HQ4EFgQUqnly22/TxRDGHOvCXZXn6k8bVZwwQgYDVR0eAQH/BDgwNqA0MAuCCWxv
      Y2FsaG9zdDANggtuZXRmbGl4Lm5ldDAKhwh/AAAB/////zAKhwhkQAAA/8AAADAP
      BgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIEC0XYN2RmYbB02pZdzN
      EMqCsnxE9exdDZ/5lpp6se/yAiEA3VNS6i/wcflnP7nJvhAo/MAY8BO897sVkd4k
      NUc2ln8=
      -----END CERTIFICATE-----
    ''
  ];
}
