{
  ffmpeg-full,
  ps,
}: [
  ffmpeg-full
  ps.PyChromecast
  ps.aiodiscover
  ps.aioesphomeapi
  ps.aiofiles
  ps.aiogithubapi
  ps.aiohomekit
  ps.aiohttp-cors
  ps.async-upnp-client
  ps.av
  ps.awesomeversion
  ps.croniter
  ps.defusedxml
  ps.distro
  ps.emoji
  ps.fnvhash
  ps.getmac
  ps.gtts
  ps.gtts-token
  ps.ha-ffmpeg
  ps.hacs-frontend
  ps.hass-nabucasa
  ps.home-assistant-frontend
  ps.mutagen
  ps.netdisco
  ps.paho-mqtt
  ps.pillow
  ps.plexapi
  ps.plexwebsocket
  ps.pyatv
  ps.pyipp
  ps.pymetno
  ps.pynacl
  ps.pyoctoprintapi
  ps.pyotp
  ps.pyserial
  ps.pysmartapp
  ps.python-ecobee-api
  ps.pyturbojpeg
  ps.pyudev
  ps.queueman
  ps.rachiopy
  ps.ring-doorbell
  ps.samsungctl
  ps.samsungtvws
  ps.scapy
  ps.semantic-version
  ps.spotipy
  ps.sqlalchemy
  ps.wakeonlan
  ps.zeroconf
]
